# [FLEET-ARCHITECT] Standardized Polyglot Dependabot
# Sync-ID: 2026-05-11-GLOBAL-001
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/02-Scenarios/go"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/03-Orchestration"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
