#!/usr/bin/env python
# coding:utf-8

"""
ESSENTIAL PROCESS:
    Audits Markdown and Wiki-links across all workspaces to identify broken references.
    
DATA FLOW:
    1. Iterates through all project workspaces.
    2. Reads 'all_links.txt' in each workspace (generated by pre-scripts).
    3. Parses Markdown links [text](target) and Wiki-links [[target]].
    4. Verifies targets against local filesystem and obsidian-brain vault.
    5. Reports broken links.

KEY PARAMETERS:
    - ROOT_DIR: Base directory for all workspaces.
    - WORKSPACES: List of workspace names to audit.
"""

from os import walk as osWalk
from os.path import join as osPathJoin
from os.path import exists as osPathExists
from os.path import dirname as osPathDirname
from re import compile as reCompile

from typing import List, Union


# ### CONFIGURATION ###

# Base paths for all workspaces
ROOT_DIR = "/Users/imac/Desktop/Bastien-Antigravity"
WORKSPACES = [
    "config-server", "distributed-config", "docker-deployment", "flexible-logger",
    "log-server", "microservice-toolbox", "notif-server", "obsidian-brain",
    "safe-socket", "tele-remote", "testing-sandbox", "universal-logger"
]

MD_LINK_RE = reCompile(r'\[(.*?)\]\((.*?)\)')
WIKI_LINK_RE = reCompile(r'\[\[(.*?)\]\]')

# -----------------------------------------------------------------------------------------------

def verify_link(source_file: str, target: str) -> Union[bool, str]:
    # Absolute file links
    if target.startswith("file:///"):
        path = target.replace("file://", "")
        return osPathExists(path)
    
    # Web links
    if target.startswith("http"):
        return "WEB" # Skip for now
    
    # Wiki-links
    # Note: Target might have an alias like [[page|alias]]
    if "|" in target:
        target = target.split("|")[0]
    
    # Wiki-links often omit extensions
    if not target.endswith(".md") and not "." in target:
        test_target = target + ".md"
    else:
        test_target = target

    # 1. Check relative to source_file
    rel_path = osPathJoin(osPathDirname(source_file), test_target)
    if osPathExists(rel_path):
        return True

    # 2. Check globally in obsidian-brain (the vault)
    brain_path = osPathJoin(ROOT_DIR, "obsidian-brain")
    # This is rough - Obsidian does a recursive search
    for root, dirs, files in osWalk(brain_path):
        # Handle links like [[folder/page]]
        if test_target in [f for f in files if f.endswith(".md")] or \
           osPathJoin(root, test_target) == osPathJoin(brain_path, test_target):
               return True
               
    # 3. Check relative to ROOT_DIR (some workspace-root links)
    abs_path = osPathJoin(ROOT_DIR, test_target)
    if osPathExists(abs_path):
        return True

    return False

# -----------------------------------------------------------------------------------------------

def audit() -> List[str]:
    results = []
    for ws in WORKSPACES:
        links_file = osPathJoin(ROOT_DIR, ws, "all_links.txt")
        if not osPathExists(links_file):
            continue
            
        with open(links_file, 'r') as f:
            for line in f:
                parts = line.strip().split(":", 2)
                if len(parts) < 3: continue
                rel_file, line_no, content = parts
                abs_source = osPathJoin(ROOT_DIR, ws, rel_file)
                
                # Check Markdown links
                for match in MD_LINK_RE.finditer(content):
                    text, target = match.groups()
                    if not verify_link(abs_source, target):
                        results.append(f"BROKEN: {ws}/{rel_file}:{line_no} -> {target}")
                
                # Check Wiki-links
                for match in WIKI_LINK_RE.finditer(content):
                    target = match.group(1)
                    if not verify_link(abs_source, target):
                        results.append(f"BROKEN_WIKI: {ws}/{rel_file}:{line_no} -> [[{target}]]")
    
    return results

# -----------------------------------------------------------------------------------------------

if __name__ == "__main__":
    broken = audit()
    for b in broken:
        print(b)
    print(f"\nAudit complete. Found {len(broken)} issues.")

